version: '3.8'

services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    ports:
      - "8000:8000"
    environment:
      - OLLAMA_ENV=production
    volumes:
      - ollama_data:/data
    restart: always

  oracle:
    image: oraclelinux:9.5
    container_name: oracle_linux
    restart: always

  db:
    image: postgres:latest
    container_name: postgres_db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=yourdatabase
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

  tika:
    image: apache/tika:latest
    container_name: tika
    ports:
      - "9998:9998"
    restart: always

volumes:
  ollama_data:
  postgres_data:
